name: Testes em múltiplos SOs

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Instalar o pytest
        run: python -m pip install pytest   

      - name: Executar testes com pytest
        run: |
            python -m unittest discover
